//
//  SimCamWeb.m
//  SimCamInject
//
//  Camera for web pages (getUserMedia) in Safari and WKWebView. WebKit
//  captures in its GPU process, which launchd starts without the simulator's
//  DYLD_INSERT_LIBRARIES, so the AVFoundation fakes never exist there. Every
//  WKWebView created in a hooked process instead gets SimCamWebShim.js, which
//  replaces getUserMedia's video with a canvas stream, and a "simcamFrame"
//  message handler that answers each request with the current frame as a
//  base64 JPEG.
//
//  WebKit is looked up at run time, so apps without it pay nothing.
//

#import <CoreVideo/CoreVideo.h>
#import <Foundation/Foundation.h>
#import <ImageIO/ImageIO.h>
#import <VideoToolbox/VideoToolbox.h>
#import <objc/message.h>
#import <objc/runtime.h>
#import <os/log.h>

#import "SimCamFrameSource.h"
#import "SimCamWeb.h"
#import "SimCamWebShim.js.h"   // generated by build.sh: SimCamWebShim_js[], SimCamWebShim_js_len

static os_log_t SCWebLog(void) {
    static os_log_t log;
    static dispatch_once_t once;
    dispatch_once(&once, ^{ log = os_log_create("jp.co.bluecode.SimCamInject", "web"); });
    return log;
}

static NSString *const kSCHandlerName = @"simcamFrame";
static char kSCInstalledKey;

/// Current frame as base64 JPEG, or nil.
static NSString *SCCurrentFrameJPEGBase64(void) {
    CVPixelBufferRef pixelBuffer = SCFrameSourceCopyFrame();
    if (!pixelBuffer) return nil;
    CGImageRef image = NULL;
    VTCreateCGImageFromCVPixelBuffer(pixelBuffer, NULL, &image);
    CVPixelBufferRelease(pixelBuffer);
    if (!image) return nil;
    NSMutableData *jpeg = [NSMutableData data];
    CGImageDestinationRef destination = CGImageDestinationCreateWithData((CFMutableDataRef)jpeg, CFSTR("public.jpeg"), 1, NULL);
    if (destination) {
        NSDictionary *options = @{ (NSString *)kCGImageDestinationLossyCompressionQuality: @0.85 };
        CGImageDestinationAddImage(destination, image, (CFDictionaryRef)options);
        if (!CGImageDestinationFinalize(destination)) jpeg = nil;
        CFRelease(destination);
    }
    CGImageRelease(image);
    return jpeg.length ? [jpeg base64EncodedStringWithOptions:0] : nil;
}

// MARK: - Message handler (WKScriptMessageHandlerWithReply)

@interface SCFrameHandler : NSObject
@end

@implementation SCFrameHandler

+ (SCFrameHandler *)shared {
    static SCFrameHandler *handler;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        Protocol *protocol = objc_getProtocol("WKScriptMessageHandlerWithReply");
        if (protocol) class_addProtocol([SCFrameHandler class], protocol);
        handler = [SCFrameHandler new];
    });
    return handler;
}

- (void)userContentController:(id)controller didReceiveScriptMessage:(id)message
                 replyHandler:(void (^)(id reply, NSString *error))replyHandler {
    static dispatch_queue_t queue;
    static dispatch_once_t once;
    dispatch_once(&once, ^{ queue = dispatch_queue_create("jp.co.bluecode.SimCamInject.web", DISPATCH_QUEUE_SERIAL); });
    void (^reply)(id, NSString *) = [replyHandler copy];
    dispatch_async(queue, ^{
        NSString *frame = [SCCurrentFrameJPEGBase64() retain];
        dispatch_async(dispatch_get_main_queue(), ^{
            reply(frame, frame ? nil : @"no frame");
            [frame release];
            [reply release];
        });
    });
}

@end

// MARK: - WKWebView hook

/// Add the shim and the frame handler to a configuration's content
/// controller, once per controller.
static void SCInstallIntoConfiguration(id configuration) {
    id controller = [configuration valueForKey:@"userContentController"];
    if (!controller || objc_getAssociatedObject(controller, &kSCInstalledKey)) return;

    Class worldClass = objc_getClass("WKContentWorld");
    Class scriptClass = objc_getClass("WKUserScript");
    SEL addHandler = NSSelectorFromString(@"addScriptMessageHandlerWithReply:contentWorld:name:");
    SEL initScript = NSSelectorFromString(@"initWithSource:injectionTime:forMainFrameOnly:inContentWorld:");
    if (!worldClass || !scriptClass || ![controller respondsToSelector:addHandler]
        || ![scriptClass instancesRespondToSelector:initScript]) {
        os_log_error(SCWebLog(), "WebKit API missing; web pages keep the system camera");
        return;
    }
    id pageWorld = ((id (*)(id, SEL))objc_msgSend)(worldClass, NSSelectorFromString(@"pageWorld"));
    NSString *source = [[[NSString alloc] initWithBytes:SimCamWebShim_js length:SimCamWebShim_js_len
                                               encoding:NSUTF8StringEncoding] autorelease];
    // WKUserScriptInjectionTimeAtDocumentStart = 0; every frame, so iframes get it too.
    id script = ((id (*)(id, SEL, id, NSInteger, BOOL, id))objc_msgSend)(
        [scriptClass alloc], initScript, source, 0, NO, pageWorld);

    @try {
        ((void (*)(id, SEL, id, id, id))objc_msgSend)(controller, addHandler, [SCFrameHandler shared], pageWorld, kSCHandlerName);
    } @catch (NSException *e) {
        // A handler of that name already exists (should not happen): leave the page alone.
        os_log_error(SCWebLog(), "could not add frame handler: %{public}@", e.reason);
        [script release];
        return;
    }
    ((void (*)(id, SEL, id))objc_msgSend)(controller, NSSelectorFromString(@"addUserScript:"), script);
    [script release];
    objc_setAssociatedObject(controller, &kSCInstalledKey, @YES, OBJC_ASSOCIATION_RETAIN);
}

void SCInstallWebKitHooks(void) {
    Class webView = objc_getClass("WKWebView");
    if (!webView) return;   // app without WebKit
    SEL sel = @selector(initWithFrame:configuration:);
    Method method = class_getInstanceMethod(webView, sel);
    if (!method) return;
    __block IMP original = method_getImplementation(method);
    IMP replacement = imp_implementationWithBlock(^id(id self, CGRect frame, id configuration) {
        if (configuration) SCInstallIntoConfiguration(configuration);
        return ((id (*)(id, SEL, CGRect, id))original)(self, sel, frame, configuration);
    });
    method_setImplementation(method, replacement);
    os_log(SCWebLog(), "web pages get the camera through getUserMedia");
}
